import React from 'react';
import './globals.css';
import { Inter } from 'next/font/google';
import { VehiclesProvider } from '@/store/store';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body>
        <VehiclesProvider>
          {children}
        </VehiclesProvider>
      </body>
    </html>
  );
}
