import React from 'react';
import './globals.css';
import { VehiclesProvider } from '@/store/store';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <VehiclesProvider>
          {children}
        </VehiclesProvider>
      </body>
    </html>
  );
}
